import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// --- HELPER FUNCTIONS FOR VECTOR GRAPHICS ---
const drawHeader = (doc, data, pageNum, totalPages) => {
    const width = doc.internal.pageSize.width;
    const height = doc.internal.pageSize.height;

    // Top Bar
    doc.setFillColor(15, 23, 42); // Slate 900
    doc.rect(0, 0, width, 40, 'F');

    // Logo / Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text("AIPIS", 14, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text("FORENSIC INVESTIGATION DIVISION", 14, 26);
    doc.text(`Doc Ref: ${data.id}`, width - 14, 18, { align: 'right' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, width - 14, 26, { align: 'right' });

    // Watermark
    doc.setTextColor(230, 230, 230);
    doc.setFontSize(60);
    doc.saveGraphicsState();
    doc.setGState(new doc.GState({ opacity: 0.05 }));
    doc.text("CONFIDENTIAL", width / 2, height / 2, { align: 'center', angle: 45 });
    doc.restoreGraphicsState();

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by AIPIS Neural Engine v4.2 • Page ${pageNum} of ${totalPages}`, width / 2, height - 10, { align: 'center' });
};

const drawRiskBadge = (doc, x, y, level) => {
    const isCrit = level.includes('CRITICAL') || level.includes('High');
    const color = isCrit ? [225, 29, 72] : [245, 158, 11]; // Rose or Amber
    doc.setFillColor(...color);
    doc.roundedRect(x, y - 4, 30, 6, 1, 1, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(level.toUpperCase(), x + 15, y, { align: 'center' });
};

// --- MAIN GENERATOR ---
export const generateReportPDF = (data) => {
    try {
        const doc = new jsPDF();
        const width = doc.internal.pageSize.width;

        // --- PAGE 1: EXECUTIVE SUMMARY ---
        drawHeader(doc, data, 1, 3);
        let y = 55;

        // 1.1 ASSET CONTEXT
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text("ASSET CONTEXT", 14, y);
        y += 5;

        doc.setDrawColor(226, 232, 240);
        doc.line(14, y, width - 14, y);
        y += 8;

        doc.setTextColor(15, 23, 42); // Slate 900
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(data.asset.name, 14, y);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.text(`Location: ${data.asset.location}`, 14, y + 5);
        doc.text(`Material: ${data.asset.material}`, 14, y + 10);

        doc.text(`Install Date: ${data.asset.asset}`, width / 2, y + 5);
        doc.text(`Last Inspection: ${data.asset.lastInspection}`, width / 2, y + 10);
        y += 20;

        // 1.2 THE VERDICT BOX
        doc.setFillColor(255, 241, 242); // Rose 50
        doc.setDrawColor(225, 29, 72); // Rose 600
        doc.roundedRect(14, y, width - 28, 40, 3, 3, 'FD');

        doc.setTextColor(225, 29, 72);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text("CRITICAL FAULT DETECTED", 20, y + 12);

        doc.setTextColor(15, 23, 42);
        doc.setFontSize(12);
        doc.text(`Classification: ${data.verdict.subtitle}`, 20, y + 22);
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text(`Confidence: ${data.verdict.confidence}% (Pattern Match Verified)`, 20, y + 30);

        // Draw Mini Logic Grid
        y += 50;
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text("ROOT CAUSE ANALYSIS (5-WHY chain)", 14, y);
        y += 8;

        data.rca.fiveWhys.forEach((why, i) => {
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            // Draw connector line
            if (i > 0) {
                doc.setDrawColor(200, 200, 200);
                doc.line(18, y - 4, 18, y - 1);
            }
            doc.text(`${i + 1}. ${why}`, 20, y);
            y += 8;
        });

        // 1.3 IMPACT TABLE
        y += 10;
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.text("OPERATIONAL IMPACT", 14, y);
        y += 5;

        const impactData = [
            ['Volume Lost', data.impact.volumeLost],
            ['Cost Estimate', data.impact.costEstimate],
            ['Regulatory', data.impact.regulatoryFine]
        ];

        autoTable(doc, {
            startY: y,
            body: impactData,
            theme: 'striped',
            headStyles: { fillColor: [15, 23, 42] },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
        });

        // --- PAGE 2: TECHNICAL FORENSICS ---
        doc.addPage();
        drawHeader(doc, data, 2, 3);
        y = 55;

        // 2.1 DATA INTEGRITY
        doc.setFontSize(12);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text("TECHNICAL FORENSICS & DATA VALIDATION", 14, y);
        y += 10;

        // Sensor Table
        const sensorBody = data.sensorHealth.map(s => [s.id, s.status, s.calibDate, s.signalQuality]);
        autoTable(doc, {
            startY: y,
            head: [['Sensor ID', 'Status', 'Last Calib', 'Signal Quality']],
            body: sensorBody,
            theme: 'plain',
            headStyles: { fillColor: [100, 116, 139] },
            styles: { fontSize: 8, cellPadding: 2 },
            columnStyles: {
                1: { fontStyle: 'bold', textColor: [225, 29, 72] } // Highlight Status
            }
        });

        y = doc.lastAutoTable.finalY + 15;

        // 2.2 FFT CHART
        doc.setFontSize(12);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text("ACOUSTIC SIGNATURE ANALYSIS", 14, y);
        y += 10;

        // Custom Vector Chart (FFT Simulation)
        doc.setFontSize(9);
        doc.text("FFT Spectrum - Vector Render", 14, y);
        y += 5;

        // Draw Chart Box
        const chartH = 60;
        const chartW = width - 28;
        doc.setDrawColor(200);
        doc.rect(14, y, chartW, chartH);

        // Draw Bars (Simulated from 0-100)
        const bars = [10, 15, 12, 5, 85, 20, 10, 5, 2, 2];
        const barW = chartW / bars.length;
        bars.forEach((val, i) => {
            const h = (val / 100) * (chartH - 10);
            const isSpike = val > 50;
            doc.setFillColor(isSpike ? 225 : 59, isSpike ? 29 : 130, isSpike ? 72 : 246); // Red if spike, Blue else
            doc.rect(14 + (i * barW) + 5, y + chartH - h, barW - 10, h, 'F');

            // Label
            doc.setTextColor(100);
            doc.setFontSize(7);
            doc.text(`${i * 5}kHz`, 14 + (i * barW) + (barW / 2), y + chartH + 5, { align: 'center' });
        });

        y += chartH + 15;

        // Detailed Data Table
        const logData = data.charts.trends.map(row => [
            row.day,
            `${row.pressure.toFixed(1)} PSI`,
            `${row.corrosion.toFixed(3)} mm/y`,
            row.corrosion > 0.1 ? 'CRITICAL' : 'STABLE'
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Day', 'Pressure', 'Corrosion Rate', 'Status']],
            body: logData,
            theme: 'grid',
            headStyles: { fillColor: [71, 85, 105] },
            styles: { fontSize: 8 },
            didParseCell: function (data) {
                if (data.section === 'body' && data.column.index === 3) {
                    if (data.cell.raw === 'CRITICAL') {
                        data.cell.styles.textColor = [225, 29, 72];
                        data.cell.styles.fontStyle = 'bold';
                    }
                }
            }
        });

        // --- PAGE 3: ADVANCED MATERIAL ANALYSIS (New Charts) ---
        doc.addPage();
        drawHeader(doc, data, 3, 4);
        y = 55;

        doc.setFontSize(12);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text("ADVANCED MATERIAL DIAGNOSTICS", 14, y);
        y += 10;

        // 3.1 SHAP FEATURE IMPORTANCE (Pie Chart)
        doc.setFontSize(10);
        doc.text("Failure Contribution Factors (SHAP Model)", 14, y);
        y += 5;

        let startAngle = 0;
        const centerX = 50;
        const centerY = y + 30;
        const radius = 25;

        data.charts.features.forEach(feat => {
            const sliceAngle = (feat.value / 100) * 360;
            const endAngle = startAngle + sliceAngle;

            // Draw Arc (Approximation with triangles for PDF simplicity)
            // Note: jsPDF native circle is easier, but slices require lines.
            // Using a simple Legend representation instead to avoid complex arc trigonometry bugs in raw PDF

            // Legend Item
            doc.setFillColor(feat.color);
            doc.circle(100, centerY - 20 + (data.charts.features.indexOf(feat) * 15), 3, 'F');
            doc.setTextColor(50);
            doc.text(`${feat.name}: ${feat.value}%`, 110, centerY - 19 + (data.charts.features.indexOf(feat) * 15));
            startAngle += sliceAngle;
        });

        // Draw a simulated circle graphical representation
        doc.setDrawColor(255);
        doc.setLineWidth(1);
        let currAngle = 0;
        data.charts.features.forEach(feat => {
            doc.setFillColor(feat.color);
            // Draw pie slice as a rect for stability or simplified sector
            // In raw PDF without external libs, arcs are hard. 
            // We will use a "Bar Stack" instead for robustness
        });

        // ALTERNATIVE: Horizontal Stacked Bar (Robust Vector)
        const stackBarW = width - 40;
        let cX = 20;
        data.charts.features.forEach(feat => {
            const w = (feat.value / 100) * stackBarW;
            doc.setFillColor(feat.color);
            doc.rect(cX, y + 5, w, 15, 'F');

            // Label inside
            if (w > 15) {
                doc.setTextColor(255);
                doc.setFontSize(8);
                doc.text(`${feat.value}%`, cX + (w / 2) - 2, y + 14);
            }
            cX += w;
        });
        y += 35;


        // 3.2 SENSOR CROSS-CORRELATION MATRIX
        doc.setFontSize(10);
        doc.setTextColor(15, 23, 42);
        doc.text("Sensor Cross-Correlation (Pearson r)", 14, y);
        y += 5;

        const corrBody = data.charts.correlations.map(c => [c.pair, c.r.toString(), c.significance]);
        autoTable(doc, {
            startY: y,
            head: [['Variable Pair', 'Correlation (r)', 'Significance']],
            body: corrBody,
            theme: 'grid',
            headStyles: { fillColor: [15, 23, 42] },
            columnStyles: {
                1: { fontStyle: 'bold', textColor: [225, 29, 72] }
            }
        });

        y = doc.lastAutoTable.finalY + 15;

        // 3.3 PRESSURE DISTRIBUTION (Histogram)
        doc.setFontSize(10);
        doc.setTextColor(15, 23, 42);
        doc.text("Pressure Stability Histogram", 14, y);
        y += 10;

        const maxCount = Math.max(...data.charts.pressureDist.map(d => d.count));
        const histH = 40;
        const histW = width - 40;
        const colW = histW / data.charts.pressureDist.length;

        // Axis Line
        doc.setDrawColor(100);
        doc.line(20, y + histH, 20 + histW, y + histH);

        data.charts.pressureDist.forEach((d, i) => {
            const h = (d.count / maxCount) * histH;
            doc.setFillColor(59, 130, 246); // Blue-500
            doc.rect(20 + (i * colW) + 2, y + histH - h, colW - 4, h, 'F');

            // Count Label
            doc.setTextColor(15, 23, 42);
            doc.text(d.count.toString(), 20 + (i * colW) + (colW / 2), y + histH - h - 2, { align: 'center' });

            // X Label
            doc.setFontSize(7);
            doc.text(d.range, 20 + (i * colW) + (colW / 2), y + histH + 8, { align: 'center' });
        });


        // --- PAGE 4: COMPLIANCE & AUDIT ---
        doc.addPage();
        drawHeader(doc, data, 4, 4);
        y = 55;

        doc.setFontSize(12);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text("COMPLIANCE & MAINTENANCE AUDIT", 14, y);
        y += 10;

        // Compliance Table
        const compBody = data.compliance.map(c => [c.standard, c.desc, c.status]);
        autoTable(doc, {
            startY: y,
            head: [['Standard', 'Description', 'Current Status']],
            body: compBody,
            theme: 'grid',
            headStyles: { fillColor: [15, 23, 42] },
            didParseCell: function (data) {
                if (data.section === 'body' && data.column.index === 2) {
                    const status = data.cell.raw;
                    if (status.includes('NON-COMPLIANT') || status.includes('Critical')) {
                        data.cell.styles.textColor = [225, 29, 72];
                        data.cell.styles.fontStyle = 'bold';
                    }
                }
            }
        });

        y = doc.lastAutoTable.finalY + 15;

        // Maintenance Log
        doc.text("RECENT MAINTENANCE HISTORY", 14, y);
        y += 5;

        const maintBody = data.maintenanceHistory.map(m => [m.date, m.type, m.technician, m.status]);
        autoTable(doc, {
            startY: y,
            head: [['Date', 'Activity', 'Tech ID', 'Result']],
            body: maintBody,
            theme: 'plain',
            headStyles: { fillColor: [100, 116, 139] }
        });

        y = doc.lastAutoTable.finalY + 20;

        // Signatures
        doc.setDrawColor(150);
        doc.line(14, y + 20, 80, y + 20);
        doc.line(width - 80, y + 20, width - 14, y + 20);
        doc.setFontSize(8);
        doc.text("Authorized Engineer Signature", 14, y + 25);
        doc.text("Plant Manager Signature", width - 80, y + 25);

        // SAVE
        doc.save(`AIPIS_Enterprise_Report_${data.id}.pdf`);
    } catch (error) {
        console.error("PDF Generation Error:", error);
        throw error;
    }
};
